### ISSUE TITLE
error when executing a run

### ISSUE THREAD

**Issue by TzurAnv** [reportportal/agent-net-gauge#1]
hi

when running a spec im receiving the following error:

Error starting plugin ReportPortal 1.0.0. fork/exec ./ReportPortal.Gauge.dll: permission denied

and no results appearing in the dashboard

**Comment by nvborisenko** [comment]
@TzurAnv , the issue should be fixed in plugin **1.0.1**.
Please verify results.

**Comment by nvborisenko** [comment]
Closing it, feel free to reopen if it doesn't work.
