### ISSUE TITLE
Unable to install the reportportal-1.1.0-preview.1 version on mac

### ISSUE THREAD

**Issue by 0sundan0** [reportportal/agent-net-gauge#10]
Hi Team, 

We are unable to install the latest preview version on mac , where installation fails with below error

Error ----------------------------------

Panicing : runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0xc0000bb940, 0x1665cc0, 0x1ca09a0)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/debug/stack.go:24 +0xa7
main.recoverPanic()
	src/github.com/getgauge/gauge/gauge.go:36 +0x57
panic(0x1665cc0, 0x1ca09a0)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/getgauge/gauge/plugin/install.InstallPluginFromZipFile(0x7ffeefbffb6a, 0x47, 0x7ffeefbffb56, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/plugin/install/install.go:159 +0x830
github.com/getgauge/gauge/cmd.glob..func10(0x1caa5c0, 0xc000162fc0, 0x1, 0x3)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/cmd/install.go:43 +0xa6
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).execute(0x1caa5c0, 0xc000162f30, 0x3, 0x3, 0x1caa5c0, 0xc000162f30)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:651 +0x24a
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1ca9900, 0xf, 0xc000170180, 0xc0001204b0)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:726 +0x2cc
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).Execute(0x1ca9900, 0x0, 0xc00017bf78)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:685 +0x2b
github.com/getgauge/gauge/cmd.Parse(0x0, 0x17638c8)
	/Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/cmd/cmd.go:158 +0x3d
main.main()
	src/github.com/getgauge/gauge/gauge.go:29 +0x3e

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
	darwin, 1.0.3, ff6c0c3
	html-report (4.0.8), java (0.7.2), screenshot (0.0.1), xml-report (0.2.1)

**Comment by nvborisenko** [comment]
This is issue https://github.com/getgauge/gauge/issues/1487 in gauge.

I already renamed our files on Releases tab, please download them again, or rename zip file yourself.
