### ISSUE TITLE
Report doesn't contain error/stacktrace message for failed scenarios

### ISSUE THREAD

**Issue by jbadeau** [reportportal/agent-net-gauge#11]
I am reopening #2.

I have installed the latest version "1.1.0-preview.1" but failed reports still only contain the name. I would expect a stacktrace and screenshots

**Comment by nvborisenko** [comment]
@jbadeau please share a screenshot where you expect error message on UI. It helps so much.

It should be on the level where steps are shown.

**Comment by jbadeau** [comment]
![issue-details](https://user-images.githubusercontent.com/152763/65942222-2102be80-e42d-11e9-9aaa-4b82da7bbdd2.png)

**Comment by jbadeau** [comment]
![issue](https://user-images.githubusercontent.com/152763/65942251-2eb84400-e42d-11e9-83cc-0ce4003ac089.png)

**Comment by nvborisenko** [comment]
Hm, I don't see scenarios at all. As I understand `Delivery Subscriptions` is specification, not scenario. Is my understanding correct?

In any case could you please share some report in file (xml, json, or html). To prevent sensitive data you could create one simple dummy scenario, and execute it.

**Comment by jbadeau** [comment]
There are scenarios but they don't upload. I am making a test example

**Comment by jbadeau** [comment]
Not working because of table

``` markdown
# Report Portal


As a tester
I want to acquire, aggregate and analyze test reports
So that I can ascertain release health

| Type   |
|--------|
| simple |

## Test
* a <Type> step
```

**Comment by jbadeau** [comment]
The previous spec does not work. Same results. The Spec is uploaded but no test runs. If i remove the table driven part then it works correctly so I assume there is an issue with the table driven scenario logic

**Comment by jbadeau** [comment]
Works fine

``` markdown
# Report Portal


As a tester
I want to acquire, aggregate and analyze test reports
So that I can ascertain release health

## Test
* a simple step
```

**Comment by nvborisenko** [comment]
So the issue is related to table driven scenarios.

In your simple scenario which is reported correctly: if make this scenario to be failed, then do you see error message in report?

**Comment by jbadeau** [comment]
In the normal case I see the stacktrace and errormessage. In the table version, there are no scenario runs, just the spec

**Comment by jbadeau** [comment]
In the step implementation I just throw an exception with a message

**Comment by jbadeau** [comment]
You fixed it?

**Comment by nvborisenko** [comment]
@jbadeau yes, new version https://github.com/reportportal/agent-net-gauge/releases/tag/1.1.0-preview.2 is available. Please verify.

**Comment by jbadeau** [comment]
Will do.

**Comment by jbadeau** [comment]
Looks good. Thanx for the great support :)
