### ISSUE TITLE
Jenkins error

### ISSUE THREAD

**Issue by jbadeau** [reportportal/agent-net-gauge#12]
Local windows reporting works fine, however; I receive and error when reporting on linux jenkins and nothing is reported.

My config:
rp_uri = http://mdzhlbmac05.standard.xyz.net:8080/api/v1
rp_project = demo
rp_uuid = e13cd8e6-9823-49c7-aff8-f8333d536bf7

Error:

[0mFailFast:[0m
[0mCouldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.[0m
[0m
[0m   at System.Environment.FailFast(System.String)[0m
[0m   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()[0m
[0m   at System.Globalization.GlobalizationMode..cctor()[0m
[0m   at System.Globalization.CultureData.CreateCultureWithInvariantData()[0m
[0m   at System.Globalization.CultureData.get_Invariant()[0m
[0m   at System.Globalization.CultureInfo..cctor()[0m
[0m   at System.StringComparer..cctor()[0m
[0m   at System.AppDomain.InitializeCompatibilityFlags()[0m
[0m   at System.AppDomain.Setup(System.Object)[0m
[0mError starting plugin ReportPortal 1.1.0. Failed to connect to plugin. Timed out connecting to 127.0.0.1:34297

**Comment by nvborisenko** [comment]
@jbadeau thanks for the issue. Could you please try https://github.com/reportportal/agent-net-gauge/releases/tag/1.1.0-preview.3, this version should resolve it.

**Comment by jbadeau** [comment]
This fixes the issue. Thanx allot
