### ISSUE TITLE
Logging of Steps

### ISSUE THREAD

**Issue by jbadeau** [reportportal/agent-net-gauge#13]
Hi,

First, thanks allot for this plugin, its very useful.

This is a feature request. According to your documentation "A typical Launch structure comprises the following elements: Suite > Test > Step > Log."

Currently this plugin does not log steps. Is this by design? If so, then I would like to request that the gauge steps are included in the reporting.

**Comment by jbadeau** [comment]
The cucumber reporter shows steps as test cases instead of logs. I think the gauge reporter should behave very similar.

**Comment by jbadeau** [comment]
Would a pull request help?

**Comment by nvborisenko** [comment]
Let's see how it will look before implementing. I am not sure how RP will calculate statistics.. scenario should be `test` type, and steps - `step` type. I will play with this structure, and if it will look good, we will apply it in gauge agent.

One more point to take into account: are we able to spread scenario output between steps?..

**Comment by jbadeau** [comment]
Yes, I didn’t think about the stats aspect :(. I will think about the structure a bit more.

I’m not exactly sure what u mean by spread scenario output?

Need to study the report portal api a bit.

**Comment by nvborisenko** [comment]
I meant if test produces some output, is this output per scenario? Or per step?

@jbadeau to help us understand what kind of information is available for plugin, please add `rp_log_enabled` property in config with `true` value. This hidden feature sends all available info from gauge core reporting. This is attached as log items in RP.

**Comment by nvborisenko** [comment]
In `v1.2.0` all steps will be reported as nested steps (new feature of RPv5).

**Comment by nvborisenko** [comment]
Done.
