### ISSUE TITLE
Support ReportPortalv5 when it will be released

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/agent-net-gauge#17]
- Waiting deployment of rp.epam.com
- And then just upgrade dependencies

**Comment by DzmitryHumianiuk** [comment]
@nvborisenko just in case

- [Reporting DevGuide](https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md)

- https://web.demo.reportportal.io

**Comment by nvborisenko** [comment]
Continued with beta packages.
