### ISSUE TITLE
Feature request: Rerunning failed test cases from gauge should post results to specific instance / last run instance of launch

### ISSUE THREAD

**Issue by 2vireddy** [reportportal/agent-net-gauge#23]
gauge has the ability to rerun failed only test cases after a execution run of all test cases, it would be helpful to push results of failed only test run to last launch or any specific launch in report portal.

**Comment by nvborisenko** [comment]
Technically this is possible, awaiting ReportPortal.Shared dependency where it should be built-in feature.

Then plugin can rely on `SpecStarting` event to understand whether launch is rerun or not. Pay attention: this kind of info is not available in `ExecutionStarting` event, only in `SpecStarting`. So plugin should deffer starting of launch, and start it as soon as new spec is starting.

**Comment by DzmitryHumianiuk** [comment]
Starting RPv5.0 API support replacement of results in previous/any launch.

We call it **Re-Run feature.** https://github.com/reportportal/reportportal/issues/363
and have it described for java clients: https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/rerun.md

similarity of test cases identified by the same UUID of test case (test method)

**Comment by iminder-singh** [comment]
As part of my test runs, I'm rerunning failed tests with command `mvn gauge:execute -Dflags=--failed` however in reportportal I can see two separate runs, one for the initial run and another for the failed test run. Does this feature need to be enabled using a property as suggested in the documentation above which would be something like `rp_rerun=true` ?
