### ISSUE TITLE
Add enable flag

### ISSUE THREAD

**Issue by iminder-singh** [reportportal/agent-net-gauge#26]
Will it be possible to add the `RP_ENABLE` env property to allow control of when logging occurs to reportportal for test runs?

Thanks

**Comment by nvborisenko** [comment]
Yes, thanks for the feature request.

**Comment by iminder-singh** [comment]
Thanks. Please let me know once this feature is available

**Comment by iminder-singh** [comment]
Thanks for this @nvborisenko! When do you plan on releasing v1.4.0?

**Comment by nvborisenko** [comment]
When all issues will be resolved, please track https://github.com/reportportal/agent-net-gauge/milestone/4

Hence these issues are pretty simple to resolve, I hope, new release is soon.
