### ISSUE TITLE
TestCaseId

### ISSUE THREAD

**Issue by jbadeau** [reportportal/agent-net-gauge#27]
Does this plugin support the new TestCaseId https://github.com/reportportal/client-java/wiki/Test-case-ID?

If not, is it planned?

**Comment by nvborisenko** [comment]
Plugin is language independent and know nothing about Java or C#.

If we want to report `TestCaseId` as a property of scenario, we should consider gauge syntax only.
At the first look tags might help:
```
# My Specification

## My Scenario 1
   Tags: TestCaseId:123, chrome
 * Step1
 * Step2
```
Plugin will be able to catch this special tag.

**Comment by jbadeau** [comment]
Hi,
Yes Gauge tags would be the way to go. I already use them for my Gauge Jira xray-report https://github.com/jbadeau/xray-report

I am currently using like this:

```markdown
## Scenario
Tags: TestKey-PROJECT-1
```

but would have no problem to align with your plugin on:

```markdown
## Scenario
Tags: TestCaseId:PROJECT-1
```

This feature is really important for traceability.

**Comment by jbadeau** [comment]
One issue would be how to report data driven tests. As you said, we cant use language runners so would prob require a Gauge grammar extension. Anyway, basic support would already be wonderful.

**Comment by jbadeau** [comment]
Many thanks for the fast release. I have also updated the Jira plugin to use the same.
