### ISSUE TITLE
Unexpected Error following retry failed tests - launch hanging

### ISSUE THREAD

**Issue by iminder-singh** [reportportal/agent-net-gauge#29]
Not sure if this is still related to the previous issue (https://github.com/reportportal/agent-net-gauge/issues/28), but I thought it would be fixed. However noticed a couple of launches hanging using the latest plugin version and in the jenkins logs got the following output. This happened following the retry of failed of some failed tests (`mvn clean install -Ptest -DinParallel=true || mvn gauge:execute -Dflags=--failed`) - I did test this scenario but probably not enough times.

>[int] Finishing to send results to Report Portal...
[int] Unexpected errors: System.AggregateException: Cannot finish launch due finishing of child items failed. (One or more errors occurred. (Cannot finish test item due starting item failed.)) (One or more errors occurred. (Cannot finish test item due starting item failed.)) (One or more errors occurred. (Cannot finish test item due starting item failed.)) (One or more errors occurred. (Cannot finish test item due starting item failed.)) (One or more errors occurred. (Cannot finish test item due starting item failed.))
[int] ---> System.AggregateException: One or more errors occurred. (Cannot finish test item due starting item failed.)
[int] ---> System.Exception: Cannot finish test item due starting item failed.
[int] ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: InternalServerError (500) POST http://1.1.1.1:8080/api/v1/test/item)
[int] ---> ReportPortal.Client.ReportPortalException: Response status code does not indicate success: InternalServerError (500) POST http://1.1.1.1:8080/api/v1/test/item
[int] ---> System.Net.Http.HttpRequestException: Response message: {"errorCode":5000,"message":"Unclassified error [query did not return a unique result: 2]"}
[int] --- End of inner exception stack trace ---
[int] at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
[int] at ReportPortal.Client.Resources.ServiceBaseResource.SendAsJsonAsync[TResponse,TRequest](HttpMethod httpMethod, String uri, TRequest request)
[int] at ReportPortal.Client.Resources.ServiceBaseResource.PostAsJsonAsync[TResponse,TRequest](String uri, TRequest request)
[int] at ReportPortal.Client.Resources.ServiceTestItemResource.StartAsync(StartTestItemRequest request)
[int] at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt)
[int] at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass22_0.<<Start>b__0>d.MoveNext()
[int] --- End of inner exception stack trace ---
[int] --- End of inner exception stack trace ---
[int] at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass27_0.<<Finish>b__0>d.MoveNext()
[int] --- End of inner exception stack trace ---
[int] --- End of inner exception stack trace ---
[int] at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass25_0.<<Finish>b__0>d.MoveNext()
[int] --- End of stack trace from previous location where exception was thrown ---
[int] at ReportPortal.Shared.Reporter.LaunchReporter.Sync()
[int] at ReportPortal.GaugePlugin.Results.Sender.Sync()
[int] at Re
[int] portPortal.GaugePlugin.ReportMessagesHandler.Kill(KillProcessRequest request, ServerCallContext context)
[int] ---> (Inner Exception #1) System.AggregateException: One or more errors occurred. (Cannot finish test item due starting item failed.)
[int] ---> System.Exception: Cannot finish test item due starting item failed.
[int] ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: InternalServerError (500) POST http://1.1.1.1:8080/api/v1/test/item)
[int] ---> ReportPortal.Client.ReportPortalException: Response status code does not indicate success: InternalServerError (500) POST http://1.1.1.1:8080/api/v1/test/item
[int] ---> System.Net.Http.HttpRequestException: Response message: {"errorCode":5000,"message":"Unclassified error [query did not return a unique result: 2]"}
[int] --- End of inner exception stack trace ---
[int] at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
[int] at ReportPortal.Client.Resources.ServiceBaseResource.SendAsJsonAsync[TResponse,TRequest](HttpMethod httpMethod, String uri, TRequest request)
[int] at ReportPortal.Client.Resources.ServiceBaseResource.PostAsJsonAsync[TResponse,TRequest](String uri, TRequest request)
[int] at ReportPortal.Client.Resources.ServiceTestItemResource.StartAsync(StartTestItemRequest request)
[int] at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt)
[int] at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass22_0.<<Start>b__0>d.MoveNext()
[int] --- End of inner exception stack trace ---
[int] --- End of inner exception stack trace ---
[int] at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass27_0.<<Finish>b__0>d.MoveNext()
[int] --- End of inner exception stack trace ---<---
[int] ---> (Inner Exception #2) System.AggregateException: One or more errors occurred. (Cannot finish test item due starting item failed.)
[int] ---> System.Exception: Cannot finish test item due starting item failed.
[int] ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: InternalServerError (500) POST http://1.1.1.1:8080/api/v1/test/item)
[int] ---> ReportPortal.Client.ReportPortalException: Response status code does not indicate success: InternalServerError (500) POST http://1.1.1.1:8080/api/v1/test/item
[int] ---> System.Net.Http.HttpRequestException: Response message: {"errorCode":5000,"message":"Unclassified error [query did not return a unique result: 3]"}
[int] --- End of inner exception stack trace ---
[int] at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
[int] at ReportPortal.Client.Resources.ServiceBaseResource.SendAsJsonAsync[TResponse,TRequest](HttpMethod httpMethod, String uri, TRequest request)
[int] at ReportPortal.Client.Resources.ServiceBaseResource.PostAsJsonAsync[TResponse,TRequest](String uri, TRequest request)
[int] at ReportPortal.Client.Resources.ServiceTestItemResource.StartAsync(StartTestItemRequest request)
[int] at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt)
[int] at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass22_0.<<Start>b__0>d.MoveNext()
[int] --- End of inner exception stack trace ---
[int] --- End of inner exception stack trace ---
[int] at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass27_0.<<Finish>b__0>d.MoveNext()
[int] --- End of inner exception stack trace ---<---
[int] ---> (Inner Exception #3) System.AggregateException: One or more errors occurred. (Cannot finish test item due starting item failed.)
[int] ---> System.Exception: Cannot finish test item due starting item failed.
[int] ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: InternalServerError (500) POST http://1.1.1.1:8080/api/v1/test/item)
[int] ---> ReportPortal.Client.ReportPortalException: Response status code does not indicate success: InternalServerError (500) POST http://1.1.1.1:8080/api/v1/test/item
[int] ---> System.Net.Http.HttpRequestException: Response message: {"errorCode":5000,"message":"Unclassified error [query did not return a unique result: 3]"}
[int] --- End of inner exception stack trace ---
[int] at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
[int] at ReportPortal.Client.Resources.ServiceBaseResource.SendAsJsonAsync[TResponse,TRequest](HttpMethod httpMethod, String uri, TRequest request)
[int] at ReportPortal.Client.Resources.ServiceBaseResource.PostAsJsonAsync[TResponse,TRequest](String uri, TRequest request)
[int] at ReportPortal.Client.Resources.ServiceTestItemResource.StartAsync(StartTestItemRequest request)
[int] at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt)
[int] at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass22_0.<<Start>b__0>d.MoveNext()
[int] --- End of inner exception stack trace ---
[int] --- End of inner exception stack trace ---
[int] at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass27_0.<<Finish>b__0>d.MoveNext()
[int] --- End of inner exception stack trace ---<---
[int] ---> (Inner Exception #4) System.AggregateException: One or more errors occurred. (Cannot finish test item due starting item failed.)
[int] ---> System.Exception: Cannot finish test item due starting item failed.
[int] ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: InternalServerError (500) POST http://1.1.1.1:8080/api/v1/test/item)
Post stage
[int] ---> ReportPortal.Client.ReportPortalException: Response status code does not indicate success: InternalServerError (500) POST http://1.1.1.1:8080/api/v1/test/item
[int] ---> System.Net.Http.HttpRequestException: Response message: {"errorCode":5000,"message":"Unclassified error [query did not return a unique result: 3]"}
[int] --- End of inner exception stack trace ---
[int] at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
[int] at ReportPortal.Client.Resources.ServiceBaseResource.SendAsJsonAsync[TResponse,TRequest](HttpMethod httpMethod, String uri, TRequest request)
[int] at ReportPortal.Client.Resources.ServiceBaseResource.PostAsJsonAsync[TResponse,TRequest](String uri, TRequest request)
[int] at ReportPortal.Client.Resources.ServiceTestItemResource.StartAsync(StartTestItemRequest request)
[int] at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt)
[int] at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass22_0.<<Start>b__0>d.MoveNext()
[int] --- End of inner exception stack trace ---
[int] --- End of inner exception stack trace ---
[int] at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass27_0.<<Finish>b__0>d.MoveNext()

**Comment by nvborisenko** [comment]
```
{"errorCode":5000,"message":"Unclassified error [query did not return a unique result: 3]"}
```

Seems server doesn't understand what scenario/test we are posting as retry because there are similar 3 scenarios/tests.

@IRE04 please help to identify these similar scenarios (with identical name and description), we will see whether we can adopt plugin to send more uniqueness data to RP.

**Comment by iminder-singh** [comment]
I've had a look at the failing scenarios and though they have unique scenario headings the common phrase is `reset password` between two different scenarios in different specs

I have `A.spec` which has the following pre-step before scenarios at the top:

# SPEC A TITLE

   |ABC       |DEF         |
   |---------|---------|
   |A             |D             |
   |B             |D             |
   |C             |D             |
* Set abc `<ABC>` and def to `<DEF>`

## Scenario 1

The failing scenario does not have any parametrisation. So the same scenario will be run 3 times with the above pre-step changing. So this may be the problem?

One of the other specs which had a failing scenario has something similar but slightly different as pre-step:

# SPEC B TITLE

   |ABC       |DEF         |GHI   | 
   |---------|---------|------|
   |A             |C            |A        |
   |A             |D            |A       |

* Set headers
   |a          |b                 |c          |
   |-------|-----------|-------|
   |`<ABC>`|`<DEF>`      |`<GHI>`  | 

* Signup with `<DEF>`

## Scenario 1

The two failing scenarios in this spec also do not have parametrisation using the above.

These are the only things I can see which are similar. Hope it helps

**Comment by iminder-singh** [comment]
In the third failing spec, I have a scenario which has a table for assertion that has similar wording. Something like this:


Scenario A
-------------------------------------------------------------------
* Step 1
* Step 2
* Step 3 - Assert
   |message                        |value   |code                            |
   |-------------------------------|---------|--------------------------------|
   |Please enter your title        |title    |cc.edit.title.blank    |
   |Please enter your first name   |firstName|cc.edit.firstName.blank|
   |Please enter your email address|email    |cc.edit.email.blank    |

**Comment by nvborisenko** [comment]
Reproduced with parameterized scenarios.

**Comment by nvborisenko** [comment]
Issue is on server side: https://github.com/reportportal/reportportal/issues/980

**Comment by iminder-singh** [comment]
Thanks, I have just updated to version 5.2 yesterday but I wonder if this is an issue with a previous version too? Trying to work out how to avoid this whilst it is still being fixed because I have a lot of tests and launches and the last thing I want are lots of hanging logs.

**Comment by nvborisenko** [comment]
@IRE04 looks like the issue is resolved, please verify. Awaiting your reply.
