### ISSUE TITLE
NullReferenceException when running data-driven specs in parallel

### ISSUE THREAD

**Issue by iminder-singh** [reportportal/agent-net-gauge#31]
Problem:

Running data-driven specs in parallel is causing NullReferenceException to be thrown on gauge versions:

`Gauge version: 1.1.1
Commit Hash: 6e0d83f
Plugins
html-report (4.0.10)
java (0.7.9)
reportportal (1.7.0)
screenshot (0.0.1)
spectacle (0.1.4)
xml-report (0.2.3)`

Tests are executed on command line using maven `mvn clean test -P<profile> -Denv=<env>`

The following exception is thrown:

`Finishing to send results to Report Portal...
Unexpected errors: System.NullReferenceException: Object reference not set to an instance of an object.
at ReportPortal.GaugePlugin.Results.Sender.Sync()
at ReportPortal.GaugePlugin.ReportMessagesHandler.Kill(KillProcessRequest request, ServerCallContext context)`

Example Spec:

Spec A
===================================
tags: abc
   |URL |
   |----|
   |URLA|
   |URLB|
   |URLC|
* Context step set values
   |a|b|c|
   |-|-|-|
   |A|B|C|
Scenario A
------------------------------------------------------------------------------
* Step 1
* Step 2
* Step 3 be "Created"
* Step 4 `<URL>`
* Step 5 assert
   |ABC|
   |---|
   |123|
   |345|
* Step 6 Assert
   |key |value|
   |----|-----|
   |a   |test1|
   |b   |test2|

**Comment by nvborisenko** [comment]
Escalated to gauge team https://github.com/getgauge/gauge/issues/1741

**Comment by nvborisenko** [comment]
New version of gauge v1.1.4 is released, @IRE04 please verify.

**Comment by iminder-singh** [comment]
Fixed.
