### ISSUE TITLE
Key-value launch attributes aren't trimmed before sending to the Report Portal

### ISSUE THREAD

**Issue by SerjPiv** [reportportal/agent-net-gauge#35]
Gauge Report Portal Plugin Version: 1.8.0
Report Portal: API Service: 5.2.2; Index Service: 5.0.7; Authorization Service: 5.2.1; Service UI: 5.2.2;

**STR:**
1. Set **rp_launch_attributes** = tag1; tag2; platform:x64; tag3
2. Run Gauge tests to initiate launch in The Report Portal
3. Check the **item_attribute** table in The Report Portal Database (select * from item_attribute where key = ' platform')

**Expected result:**
The launch attributes key is trimmed.

**Actual result:**
The launch attributes key isn't trimmed and contains the leading space. It breaks The Report Portal launches filtering using the launch attributes key. The expected launch doesn't appear in the filtering results.

**Comment by nvborisenko** [comment]
Thanks.

Fixed in https://github.com/reportportal/commons-net/commit/3269390bdab5b852dce0ad6593b532b87874777c, will be implicitly included in the next release.

@SerjPiv, I think this is minor bug due you can avoid it on your side. This issue is still open until shared dependency is released.
