### ISSUE TITLE
Test retried via Gauge --max-retries-count flag are reported as different tests in Report Portal

### ISSUE THREAD

**Issue by dnet1** [reportportal/agent-net-gauge#36]
Tests executed with retries using Gauge --max-retries-count flag (`gauge run --max-retries-count=<number of retries>`) are shown in Report Portal as separate tests, not several retries of the same test.

Gauge --max-retries-count flag description [here](https://docs.gauge.org/execution.html?os=linux&language=javascript&ide=vscode#rerun-failed-scenarios-by-using-max-retries-count).

Expected all test retried via --max-retries-count mechanism to be reported as retries of the same test. The same way it works for Gauge reruns executed with --failed flag.

To reproduce: create a spec with failing test and run it via `gauge run --max-retries-count=3`

**Comment by nvborisenko** [comment]
Fixed in 1.9.0, will be available soon in 1-2 days.
