### ISSUE TITLE
Error : signal: segmentation fault with reportportal plugin when running tests using gauge-java-docker

### ISSUE THREAD

**Issue by iminder-singh** [reportportal/agent-net-gauge#37]
**Description:**

When running tests using gauge-java-docker (https://github.com/sitture/docker-gauge-java), reportportal fails to start. The following error is outputted:

```
Error occurred while waiting for plugin process to finish.
Error : signal: segmentation fault
Error starting plugin ReportPortal 1.9.0. timed out connecting to reportportal
```

As suggested, libc6-compat is installed (https://github.com/sitture/docker-gauge-java/blob/master/base/Dockerfile#L23) but this has not resolved the issue above.

**Steps to recreate:**

1. Use sample gauge_maven project: https://github.com/imindersingh/gauge-maven
2. Update reportportal config in env properties
3. Run tests using:

```
docker run --rm -it -v $(pwd):/usr/src/app -v ~/.m2:/root/.m2 -e RP_ENABLED=true -e ReportPortal_TraceLevel=Verbose sitture/docker-gauge-java:latest mvn clean test
```
Gauge versions from the docker image:

```
Gauge version: 1.1.4
Commit Hash: c982558

Plugins
-------
html-report (4.0.12)
java (0.7.13)
reportportal (1.9.0)
screenshot (0.0.1)
xml-report (0.2.3)
```

**Comment by nvborisenko** [comment]
Support of alpine is added in v1.10.0

```
apk add libstdc++
apk add libintl

wget https://github.com/reportportal/agent-net-gauge/releases/download/1.10.0/reportportal-1.10.0-linux-musl-x64.zip
gauge install reportportal -f reportportal-1.10.0-linux-musl-x64.zip
```

Please verify on your side.

**Comment by haroon-sheikh** [comment]
Thanks @nvborisenko for the quick response. I've now updated sitture/docker-gauge-java:latest image with linux-musl version and it seems to be working. Will let you know if there's any other issues.
