### ISSUE TITLE
Tags on specification level are not applied to scenario level 

### ISSUE THREAD

**Issue by elenkuz** [reportportal/agent-net-gauge#38]
**Preconditions:** 
1. Gauge runner is used.
2. There is a specification with two test scenarios: specification has its own tags and each test scenario also has its tags.

![gauge_specification_with_tests](https://user-images.githubusercontent.com/19586170/98672492-91814c00-235e-11eb-8b80-c7f0c3ab3bfb.png)

**Actual Result:**
In Report Portal in each test scenario there is only its own tag present (e.g. android-case-id:5555) without tags from specification (owner: SomeTeam, tag:android). 

![specification_in_rp](https://user-images.githubusercontent.com/19586170/98672513-98a85a00-235e-11eb-9915-0be7221c964a.png)

![tests_tags_actual](https://user-images.githubusercontent.com/19586170/98672541-a3fb8580-235e-11eb-8691-88b204e94061.png)

**Expected Result:**
In Report Portal in each test scenario there are all tags from specification + tags from test scenario.
So tags for one test should be next: android-case-id:5555, owner: SomeTeam, tag: android.

![test_ tags_expected](https://user-images.githubusercontent.com/19586170/98672624-bd9ccd00-235e-11eb-9c7f-24c6532a6485.png)

![item_details_expected_result](https://user-images.githubusercontent.com/19586170/98672907-33a13400-235f-11eb-9e82-5feccb4e3391.png)

**Comment by nvborisenko** [comment]
Tags for specification comes to specification in RP.

![image](https://user-images.githubusercontent.com/22616990/98682397-ee87fc80-2374-11eb-943b-06df9f8798be.png)

Looking forward any other opinions whether we need duplicate specification tags at scenario level.

**Comment by Dmitriy85** [comment]
> Tags for specification comes to specification in RP.
> 
> ![image](https://user-images.githubusercontent.com/22616990/98682397-ee87fc80-2374-11eb-943b-06df9f8798be.png)
> 
> Looking forward any other opinions whether we need duplicate specification tags at scenario level.

The idea is to have relation between scenario and specification tags. For example I have tag owner:Jim - on spec level, I'd like to be able to link this owner to all scenario names inside this specification. Hope it makes sense to you @nvborisenko

**Comment by nvborisenko** [comment]
Personally I don't mind. Why not.

**Comment by Dmitriy85** [comment]
@nvborisenko any updates, any ETA?

**Comment by nvborisenko** [comment]
No ETA, I do it when time allows me

**Comment by dnet1** [comment]
From the Gauge [documentation](https://docs.gauge.org/writing-specifications.html?os=linux&language=javascript&ide=vscode#longstart-tags) on tags:

_Both scenarios and specifications can be separately tagged, however, only one set of tags can be added to a single specification or scenario. **A tag applied to a spec automatically applies to a scenario as well.**_

So I believe it makes sense to have the same logic in reportportal plugin.
