### ISSUE TITLE
Test Scenario is marked as STEP in reportal portal data base

### ISSUE THREAD

**Issue by elenkuz** [reportportal/agent-net-gauge#39]
**Preconditions:**

Gauge runner is used.
There is a specification with two test scenarios.

![gauge_specification_with_tests](https://user-images.githubusercontent.com/19586170/98674134-05245880-2361-11eb-98d7-80bc7cb628b3.png)

**Actual result:**
 "Scenario Heading 1" is recorded into database reportportal.test_item table with Type '**STEP**'. 

![test](https://user-images.githubusercontent.com/19586170/98677889-5e42bb00-2366-11eb-90cc-70bd91e60a23.png)

![db](https://user-images.githubusercontent.com/19586170/98677361-97c6f680-2365-11eb-9725-80a3b55fef72.png)

**Expected result:**
 "Scenario Heading 1" is recorded into database reportportal.test_item table with Type '**TEST**'. 
As it is not a step, but name of test scenario.

**Comment by nvborisenko** [comment]
Historical stuff. I need verify impact if we change item type from `Step` to `Test`.

**Comment by elenkuz** [comment]
thank you. Please, update when you will understand the impact

**Comment by nvborisenko** [comment]
Historical stuff is still reproducible. If we would report scenarios with TEST type, then scenarios cannot be explored via clicking on total stats.

![image](https://user-images.githubusercontent.com/22616990/99916372-feabbe80-2d1a-11eb-88c0-93825d3ed1e8.png)

And then no results found:

![image](https://user-images.githubusercontent.com/22616990/99916376-0a978080-2d1b-11eb-8d65-4e793371da04.png)
