### ISSUE TITLE
Gauge Report portal plugin for Java projects

### ISSUE THREAD

**Issue by deepesh1511** [reportportal/agent-net-gauge#62]
Is there a Gauge Report portal plugin for Java projects?

**Comment by nvborisenko** [comment]
This plugin is language agnostic, you can use it if you run tests with gauge and any language which gauge supports. Just try.

**Comment by tirupradeep1** [comment]
The Gauge Report Portal plugin facilitates seamless integration between Gauge and Report Portal, enabling you to manage and analyze test results effectively for your Java projects.
