### ISSUE TITLE
executing scenario resulting with error 

### ISSUE THREAD

**Issue by TzurAnv** [reportportal/agent-net-gauge#7]
cant manage to execute a scenario and receive result at the reportportal web UI 
tried several configuration(i used the 'uuid' from the 'profile' of the user i used in the 'reportportal' portal):

rp_uri = https://rp.epam.com/api/v1
rp_project = superadmin_personal
rp_uuid = 2f954b1f-7af3-437a-9bc9-aac3bf501a39

result:
Unexpected response status code. Request URI: https://rp.epam.com/api/v1/superadmin_personal/launch
Response Body: {"error":"invalid_token","error_description":"2f954b1f-7af3-437a-9bc9-aac3bf501a39"} ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).

rp_uri = http://localhost:8080
rp_uuid = 2f954b1f-7af3-437a-9bc9-aac3bf501a39
rp_launch = superadmin_TEST_EXAMPLE
rp_project = superadmin_personal

resulting with:
... System.Xml.XmlException: Encountered unexpected character '<'.

**Comment by filland** [comment]
@TzurAnv did you see this ? 
https://github.com/reportportal/example-net-gauge

**Comment by nvborisenko** [comment]
The first configuration is correct, but you don't have enough permissions. Verify your token.

The second configuration is incorrect, you forgot add `api/v1` in url.

**Comment by nvborisenko** [comment]
Closing it, feel free to reopen if it doesn't work.
