### ISSUE TITLE
ReportPortal Shows all Specs as Passed, even though the spec has failed.

### ISSUE THREAD

**Issue by 0sundan0** [reportportal/agent-net-gauge#8]
Hi Team, 

I am facing issues with the gauge integration with Report Portal, where the results uploaded to Gauge shows incorrect results. The ReportPortal shows all the specs as passed, even though the TCs failed. Please find below the details of Gauge version that i have in my environment. Any help will be highly appreciated

Gauge version: 1.0.5

Plugins
html-report (4.0.8) java (0.7.2) reportportal (1.0.1) screenshot (0.0.1) xml-report (0.2.1)

**Comment by nvborisenko** [comment]
Just to make sure: you have failed scenarios, but specification is passed. Is it true?

**Comment by 0sundan0** [comment]
I have 2 specs,out of which one spec has passed and the other has failed(Failed due a failed scenario). The gauge report shows correct result as 1 passed and 1 failed, however the result that shows up in reportportal shows 2specs as passed

**Comment by nvborisenko** [comment]
Fixed in 1.1.0-preview.1
