### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by jbadeau** [reportportal/agent-net-gauge#9]
Can we expect any issues to be fixed here or is development stopped?

**Comment by nvborisenko** [comment]
This is not dead. Initially it was created as proof of we can create agent for gauge, and it was successful. Development of this agent is in "lazy" state due gauge is not so popular. Actually I don't see overall picture and cannot prioritize issues properly. Please help me here. I see #2 as major issue, must be fixed.

@jbadeau please point which issues should be fixed, and what new issues you found. I will fix all them as soon as possible. Thanks.

**Comment by jbadeau** [comment]
Thats good news. I am away for the week but will report our current issues on Monday next week.

**Comment by nvborisenko** [comment]
1.1.0-preview.1 version is released with all fixed issues. Please verify and create new issues.
